# Generated by Django 3.1.4 on 2020-12-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.DateTimeField(verbose_name='Ecalendatnd time'),
        ),
    ]
