# Generated by Django 3.1.4 on 2020-12-10 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0002_auto_20201210_1716'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
