# Generated by Django 3.1.4 on 2020-12-10 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0003_delete_event'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Calendar',
            new_name='Calendars',
        ),
    ]
