# Generated by Django 3.1.4 on 2020-12-10 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0004_auto_20201210_1749'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Calendars',
            new_name='Calendar',
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('start', models.DateTimeField(verbose_name='Start time')),
                ('end', models.DateTimeField(verbose_name='End time')),
                ('allDay', models.BooleanField(default=True, verbose_name='All day event')),
                ('type_of_event', models.CharField(choices=[('D', 'Duty'), ('S', 'Sick Leave'), ('V', 'Vacation')], max_length=2)),
                ('notes', models.CharField(max_length=1023, verbose_name='Notes')),
                ('calendar_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendars.calendar')),
            ],
        ),
    ]
